wms(mysql)/Models/ordering.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms_mysql_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordering
    {
        public int Customer_ID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public int PutAway_Receiving_Control_ { get; set; }
        public string Item_Name { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<long> Number_of_Items { get; set; }
        public Nullable<long> Number_of_order { get; set; }
        public int column_ID { get; set; }
        public string column_name { get; set; }
    }
}

wms(mysql)/Controllers/orderingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using wms_mysql_.Models;

namespace wms_mysql_.Controllers
{
    public class orderingsController : Controller
    {
        private wms_final_databaseEntities27 db = new wms_final_databaseEntities27();

        // GET: orderings
        public ActionResult Index(string textbox)
        {
            var name = from m in db.orderings
                       where m.Customer_Name == textbox
                       select m;
            return View(name.ToList());
        }
        public ActionResult Confirm(picking pk, int id, string number_order)
        {   
            ordering order = db.orderings.Find(id);
            int number = unchecked((int)order.Number_of_Items);
            int numberoforders=int.Parse(number_order);
            number = number - numberoforders;
            char[] pwd = "1234567890987654321".ToCharArray();
            Random rnd = new Random();
            string id1 = "";
            for (int i = 0; i < 9; i++)
            {
                id1 += pwd[rnd.Next(0, 9)].ToString();
            }
             var controlnumber = Convert.ToInt32(id1);
            order.Number_of_Items = number;
            db.Entry(order).State = EntityState.Modified;
            pk.Customer_ID = order.Customer_ID;
            pk.Customer_Name = order.Customer_Name;
            pk.Item_ID = order.Item_ID;
            pk.Item_Name = order.Item_Name;
            if(numberoforders>number)
            {
                pk.Number_of_Items=number;
            }
            pk.Number_of_Items = numberoforders;
            pk.Ordering_PutAway_Receiving_Control_ = controlnumber;
            pk.column_ID = order.column_ID;
            pk.column_name = order.column_name;
            db.pickings.Add(pk);
            if(order.Number_of_Items<=0)
            {
                db.orderings.Remove(order);
            }
            db.SaveChanges();
           return RedirectToAction("Index");
        }

        // GET: orderings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ordering ordering = db.orderings.Find(id);
            if (ordering == null)
            {
                return HttpNotFound();
            }
            return View(ordering);
        }

        // GET: orderings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: orderings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Customer_ID,Item_ID,PutAway_Receiving_Control_,Item_Name,Customer_Name,Number_of_order")] ordering ordering)
        {
            if (ModelState.IsValid)
            {
                db.orderings.Add(ordering);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ordering);
        }

        // GET: orderings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ordering ordering = db.orderings.Find(id);
            if (ordering == null)
            {
                return HttpNotFound();
            }
            return View(ordering);
        }

        // POST: orderings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Customer_ID,Item_ID,PutAway_Receiving_Control_,Item_Name,Customer_Name")] ordering ordering)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ordering).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ordering);
        }

        // GET: orderings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ordering ordering = db.orderings.Find(id);
            if (ordering == null)
            {
                return HttpNotFound();
            }
            return View(ordering);
        }

        // POST: orderings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ordering ordering = db.orderings.Find(id);
            db.orderings.Remove(ordering);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

wms(mysql)/Views/orderings/Create.cshtml
@model wms_mysql_.Models.ordering

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ordering</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Customer_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PutAway_Receiving_Control_, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PutAway_Receiving_Control_, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PutAway_Receiving_Control_, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("number of order", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number_of_order, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number_of_order, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wms(mysql)/Views/orderings/Delete.cshtml
@model wms_mysql_.Models.ordering

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ordering</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

wms(mysql)/Views/orderings/Details.cshtml
@model wms_mysql_.Models.ordering

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ordering</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PutAway_Receiving_Control_ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

wms(mysql)/Views/orderings/Edit.cshtml
@model wms_mysql_.Models.ordering

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ordering</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Customer_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.PutAway_Receiving_Control_)

        <div class="form-group">
            @Html.LabelFor(model => model.Item_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wms(mysql)/Views/orderings/Index.cshtml
@model IEnumerable<wms_mysql_.Models.ordering>

@{
    ViewBag.Title = "Index";
}
<style type="text/css">
    #textbox {
        border-radius: 5px;
        width: 250px;
        height: 33px;
        float: right;
        margin: 10px 10px 10px;
        color: gray;
        font-variant-caps: all-petite-caps;
    }

    table {
        border-collapse: collapse;
        /*width: 100%;*/
        width: 900px;
        position: center;
        box-shadow: 5px 8px 15px 6px rgba(0,0,0,0.2);
    }

    div#background {
            border-radius: 20px;
            margin-top: 10px;
            display: inline-block;
            background: #DCDCDC;
            flood-opacity: initial;
            width: 930px;
            height: auto;
            position: center;
        }

     div#grad1 {
            border-radius: 10px;
            /*background: white;*/ /* For browsers that do not support gradients */
            background: linear-gradient(white, lightgray); /* Standard syntax (must be last) */
            width: 900px; height: auto;
            margin: 10px auto;
        }

         div#grad2 {
            border-radius: 10px;
            /*background: white;*/ /* For browsers that do not support gradients */
            background: linear-gradient(white, lightgray); /* Standard syntax (must be last) */
            width: 900px; height: auto;
            margin: 10px auto;
        }

      td {
            line-height: 22px;
            padding: 10px;
            text-align: center;
            border-bottom: 1px solid darkgray;
            width: 900px;
        }

        tr:hover {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid darkgray;
            width: 900px;
            font-style: italic;
            font-stretch: extra-expanded;
            font-family: 20px;
            /*transition-delay: .09s;*/
            color: white;
            background-color: darkgray;
            transition: all 0.1s ease-in-out;
            height: 60px;
        }
        .button1 {
            border-radius: 5px;
            font-variant-caps: all-petite-caps;
            background: lightgray;
        }


        tr:hover {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid darkgray;
            width: 900px;
            font-style: italic;
            font-stretch: extra-expanded;
            font-family: 20px;
            /*transition-delay: .09s;*/
            color: white;
            background-color: darkgray;
            transition: all 0.1s ease-in-out;
            height: 60px;
        }

        th {

            padding: 8px;
            text-align: center;
            border-bottom: 1px solid darkgray;
            width: 900px;
            font-weight: bold;
            font-variant-caps: all-petite-caps;
            font-size: 17px;
        }
    
</style>


<h1>Ordering</h1>


@using (Html.BeginForm())
{   
}
@Html.Action("Details", "customers")
<div id="background">
    <div id="grad2">
        @using (Html.BeginForm())
        {
            @*<label>Customer Name</label>*@
    <input type="text" id="textbox"  name="textbox" onkeydown="if(event.keyCode==13){this.form.submit();}" placeholder="Customer Name:" />
        }

        <table>
            <tr>
                <th>
                    @Html.DisplayName("Item Name")
                </th>
                <th>
                    @Html.DisplayName("Customer Name")
                </th>
                <th>
                    @Html.DisplayName("Number of Items")
                </th>
                <th></th>
            </tr>
        </table>
    </div>

<div id="grad1">
    @foreach (var item in Model)
    {

        <table>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Item_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Number_of_Items)
                    @*<input type="text" id="txtlinequantity-<%: item.Number_of_order %>" name="txtlinequantity-<%: item.ProductID %>" value="" onchange="ChangeBrowseQuantity('txtlinequantity-<%: item.ProductID %>');" style="width:36px; border:3px solid Black;" class="BrowseQuantityTextBox" />*@
                </td>
                <td>
                    @using (Html.BeginForm("Confirm", "orderings", new { id = item.PutAway_Receiving_Control_ }, FormMethod.Post))
                    {
                        <input type="number" name="number_order" required />
                        <input type="submit" class="button1" value="Add" />

                    }

                </td>
            </tr>
        </table>
    @*</div>*@
    @*</div>*@
    }





