wms(mysql)/Models/issuance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms_mysql_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuance
    {
        public int Customer_ID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public string Picker_Name { get; set; }
        public string Item_Name { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<long> Number_of_Items { get; set; }
        public int Picking_Ordering_PutAway_Receiving_Control_ { get; set; }
        public int column_ID { get; set; }
        public string column_name { get; set; }
        public string date { get; set; }
    }
}

wms(mysql)/Controllers/issuancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using wms_mysql_.Models;

namespace wms_mysql_.Controllers
{
    public class issuancesController : Controller
    {
        private wms_final_databaseEntities27 db = new wms_final_databaseEntities27();
        //public JsonResult GetStudents(string term)
        //{
        //    List<string> customers;
        //    customers = db.customers.Where(x => x.Customer_Name.StartsWith(term))
        //        .Select(y => y.Customer_Name).ToList();
        //    return Json(customers, JsonRequestBehavior.AllowGet);
        //}
        public ActionResult Confirm(int id, int columnid, string columnname,column col)
        {
            issuance issue = db.issuances.Find(id);
            col.Column_ID = columnid;
            col.Column_Name = columnname;
            db.columns.Add(col);
            db.SaveChanges();
            //db.issuances.Remove(issue);
            db.SaveChanges();
            
            return View();
        }
        // GET: issuances
        public ActionResult Index()
        {
            var issuances = db.issuances.ToList();
            return View(issuances.ToList());
        }
        public ActionResult table(int id)
        {   
            //var issuances = db.issuances.ToList();
            var issuances = from m in db.issuances
                            where m.Picking_Ordering_PutAway_Receiving_Control_ == id
                            select m;

            return View(issuances.ToList());
        }

        // GET: issuances/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            issuance issuance = db.issuances.Find(id);
            
           
            if (issuance == null)
            {
                return HttpNotFound();
            }
            return View(issuance);
        }

        // GET: issuances/Create
        public ActionResult Create()
        {
            ViewBag.Picking_Ordering_PutAway_Receiving_Control_ = new SelectList(db.pickings, "Ordering_PutAway_Receiving_Control_", "Ordering_PutAway_Receiving_Control_");
            return View();
        }

        // POST: issuances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Customer_ID,Item_ID,Picking_Ordering_PutAway_Receiving_Control_,Picker_Name,Plate_Number,Temp,ContainerNumber")] issuance issuance,int id)
        {
            if (ModelState.IsValid)
            {
                //db.issuances.Add(issuance);
                issuancelog issue = new issuancelog();
                issuance iss = db.issuances.Find(id);
                column col = new column();
                issue.ControlNumber = id;
                issue.Customer_ID = iss.Customer_ID;
                issue.Item_ID = iss.Item_ID;
                col.Column_ID = iss.column_ID;
                col.Column_Name = iss.column_name;
                db.columns.Add(col);
                db.issuancelogs.Add(issue);
                db.issuances.Remove(iss);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Picking_Ordering_PutAway_Receiving_Control_ = new SelectList(db.pickings, "Ordering_PutAway_Receiving_Control_", "Ordering_PutAway_Receiving_Control_", issuance.Picking_Ordering_PutAway_Receiving_Control_);
            return View(issuance);
        }

        // GET: issuances/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            issuance issuance = db.issuances.Find(id);
            if (issuance == null)
            {
                return HttpNotFound();
            }
            ViewBag.Picking_Ordering_PutAway_Receiving_Control_ = new SelectList(db.pickings, "Ordering_PutAway_Receiving_Control_", "Ordering_PutAway_Receiving_Control_", issuance.Picking_Ordering_PutAway_Receiving_Control_);
            return View(issuance);
        }

        // POST: issuances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Customer_ID,Item_ID,Picking_Ordering_PutAway_Receiving_Control_,Picker_Name")] issuance issuance)
        {
            if (ModelState.IsValid)
            {
                db.Entry(issuance).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Picking_Ordering_PutAway_Receiving_Control_ = new SelectList(db.pickings, "Ordering_PutAway_Receiving_Control_", "Ordering_PutAway_Receiving_Control_", issuance.Picking_Ordering_PutAway_Receiving_Control_);
            return View(issuance);
        }

        // GET: issuances/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            issuance issuance = db.issuances.Find(id);
            if (issuance == null)
            {
                return HttpNotFound();
            }
            return View(issuance);
        }

        // POST: issuances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            issuance issuance = db.issuances.Find(id);
            db.issuances.Remove(issuance);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

wms(mysql)/Views/issuances/Create.cshtml
@model wms_mysql_.Models.issuance
<style type="text/css">
    #textbox3 {
        margin-left: 140px;
        margin-top: -6%;
        display: block;
        width: 290px;
        height: 30px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555555;
        vertical-align: middle;
        background-color: #ffffff;
        border: 1px solid #cccccc;
        border-radius: 4px;
    }

    #textbox4 {
        margin-top: -3%;
        margin-left: 140px;
        display: block;
        width: 290px;
        height: 30px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555555;
        vertical-align: middle;
        background-color: #ffffff;
        border: 1px solid #cccccc;
        border-radius: 4px;
        margin-bottom: 25px;
    }

    #textbox {
        display: none;
    }

    .button1 {
        border-radius: 1px;
        border: 1px #2e83cb;
        background-color: #237ad9;
        color: #ffffff;
        padding: 5px 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 10px;

        margin-left: 50px;
    }

    .field1 {
        width: 600px;
        border: thin solid;
        float: right;
        text-align: left;
    }



    .field2 {
        width: 500px;
        border: thin solid;
        float: left;
        text-align: center;
    }

    /*#label {
                padding-top: 7px;
                margin-top: 0;
                margin-bottom: 0;
            }*/

    div.table {
        display: inline-block;
        border: 3px solid lightgray;
        border-radius: 20px;
        background: white;
        width: 900px;
        padding-left: 5em;
        text-align: left;
        box-shadow: 5px 8px 15px 6px rgba(0,0,0,0.2);
        margin-top: 10px;
    }

    div.table2 {
        display: inline-block;
        border: 3px solid lightgray;
        border-radius: 20px;
        background: white;
        width: 900px;
        height: auto;
        padding-left: 5em;
        text-align: left;
        box-shadow: 5px 8px 15px 6px rgba(0,0,0,0.2);
        margin-bottom: 10px;
    }

    div.table3 {
        border-radius: 20px;
        margin-top: 10px;
        display: inline-block;
        background: #DCDCDC;
        flood-opacity: initial;
        width: 930px;
        height: 630px;
        position: center;
        height: auto;
    }

    h1 {
        padding: -2em;
        text-shadow: 3px 3px 3px gray;
        font-family: initial;
        box-shadow: 15px 8px 15px 3px rgba(0,0,0,0.2);
        height: 40px;
        width: 930px;
        margin: 10px auto;
        margin-bottom: 10px;
    }
    /*----------------------------------------------------------------------------*/
     div.popup-position {
                position: fixed;
                top: 0;
                left: 0;
                background: rgba(0,0,0,0.7);
                width: 100%;
                height: 100%;
                display: none;
            }

            div#popup-wrapper {
                width: auto;
                height: auto;
                margin: 70px 70px;
                text-align: center;
            }

            button {
                border-radius: 5px;
                font-variant-caps: all-petite-caps;
            }

                button:hover {
                    border-radius: 5px;
                    transition: all 0.9s ease-in-out;
                }

            table {
                border-collapse: collapse;
                /*width: 100%;*/
                width: 900px;
                position: center;
                box-shadow: 5px 8px 15px 6px rgba(0,0,0,0.2);
                div #grad1;

            {
                border-radius: 10px;
                height: 200px;
                /*background: white;*/ /* For browsers that do not support gradients */
                background: linear-gradient(white, lightgray); /* Standard syntax (must be last) */
                width: 900px;
                height: auto;
                margin: 10px auto;
            }

            div#background {
                border-radius: 20px;
                margin-top: 10px;
                display: inline-block;
                background: #DCDCDC;
                flood-opacity: initial;
                width: 930px;
                height: auto;
                position: center;
            }

            label {
                display: block;
                border: 1px solid lightgray;
                background: lightgray;
                width: 100px;
                height: 30px;
                color: black;
                margin-bottom: 30px;
                margin-right: 30px;
                border-radius: 8px;
                float: right;
                text-decoration-style: none;
                text-align: center;
                padding: 3px 3px;
            }

                label:hover {
                    background: white;
                    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                }


            a {
                text-decoration: none;
                color: black;
                font-family: inherit;
                font-size: 13px;
            }

                a:hover {
                    text-decoration: none;
                    box-decoration-break: slice;
                    color: black;
                }

            form {
                float: right;
                /*margin-left: -10px;*/
                font-weight: bolder;
                font-size: 50px;
                color: white;
                margin: 0;
            }

                form a {
                    color: white;
                }
</style>
<script type="text/javascript">
    function toggle_visibility(id) {
        var e = document.getElementById(id);
        if (e.style.display == 'block')
            e.style.display = 'none';
        else
            e.style.display = 'block';
    }
   
</script>


<h1>Issuance</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="table3">
        <div class="form-horizontal">
            <div class="table">
                @Html.Action("Details", "issuances")
                <h4>issuance</h4>
                <hr/>
                <div class="form-group">
                    @Html.LabelFor(model => model.Picker_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Picker_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Picker_Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p>
                    <label for="Date" class="control-label col-md-2">Exit Date</label>
                    <input class="text-box single-line" id="Date" name="Date" type="text" required />
                </p>
            </div>
            
            <div class="table2">
                <div class="form-group">
                </div>
                @*@Html.Action("Create", "issuancelogs")*@
                @Html.Action("table", "issuances")
            </div>
        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#Date").datepicker();
            });
        </script>

    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="~/Scripts/jquery-ui.min.js" type="text/javascript"></script>
<link href="~/Content/jquery-ui.min.css" rel="stylesheet" type="text/css" />
}

wms(mysql)/Views/issuances/Delete.cshtml
@model wms_mysql_.Models.issuance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>issuance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picker_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picker_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picking_Ordering_PutAway_Receiving_Control_)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picking_Ordering_PutAway_Receiving_Control_)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

wms(mysql)/Views/issuances/Details.cshtml
@model wms_mysql_.Models.issuance
<style type="text/css">
     div.table4 {
                border-radius: 50px;
                margin-top:1%;
                margin-left:10%;
                margin-right:5%;
                display: inline-block;
                background: #DCDCDC;
                flood-opacity: initial;
                width: 500px;
                height: 630px;
                position: center;
                height:auto;
                text-align:center;
                text-decoration:solid;
            }
    dt .control1{
         text-decoration:solid;
         text-emphasis-color:#3870d4;
         font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
         
     }
     dd.control{
         text-decoration:solid;
         font:italic;
         font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
         font-size:larger;
         
     }
</style>
<div>
    <div class="table4">
        <h2>Issuance Details</h2>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Customer Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer_Name)
            </dd>
            <dt>
                @Html.DisplayName("Customer ID")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer_ID)
            </dd>

            <dt>
                @Html.DisplayName("Item Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Item_Name)
            </dd>

            <dt>

                @Html.DisplayName("Item  ID")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Item_ID)
            </dd>

            

            @*<dt>
                @Html.DisplayNameFor(model => model.Picker_Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Picker_Name)
            </dd>*@

            

            

            @*<dt>
                @Html.DisplayNameFor(model => model.Number_of_Items)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Number_of_Items)
            </dd>*@
            <dt class="control1">
                @Html.DisplayName("Control #")
            </dt>

            <dd class="control">
                @Html.DisplayFor(model => model.Picking_Ordering_PutAway_Receiving_Control_)
            </dd>

        </dl>
    </div>
</div>
<p>
</p>

wms(mysql)/Views/issuances/Edit.cshtml
@model wms_mysql_.Models.issuance

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>issuance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Customer_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Picking_Ordering_PutAway_Receiving_Control_)

        <div class="form-group">
            @Html.LabelFor(model => model.Picker_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picker_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picker_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wms(mysql)/Views/issuances/Index.cshtml
@model IEnumerable<wms_mysql_.Models.issuance>
<style type="text/css">
    h1 {
        padding: -2em;
            text-shadow: 3px 3px 3px gray;
            font-family: initial;
            box-shadow: 15px 8px 15px 3px rgba(0,0,0,0.2);
            height: 40px;
            width: 930px;
            margin: 10px auto;
            margin-bottom: 25px;
        }

    table {
        border-collapse: collapse;
        /*width: 100%;*/
        width: 900px;
        position: center;
        box-shadow: 5px 8px 15px 6px rgba(0,0,0,0.2);
    }

    td {
        line-height: 22px;
        padding: 10px;
        text-align: center;
        border-bottom: 1px solid darkgray;
        width: 900px;
    }

    tr:hover {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid darkgray;
        width: 900px;
        font-style: italic;
        font-stretch: extra-expanded;
        font-family: 20px;
        /*transition-delay: .09s;*/
        color: white;
        background-color: darkgray;
        transition: all 0.1s ease-in-out;
        height: 60px;
    }

    th {
        background: -moz-linear-gradient(top, #F0F0F0 0, #DBDBDB 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #F0F0F0), color-stop(100%, #DBDBDB));
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#F0F0F0', endColorstr='#DBDBDB', GradientType=0);
        border: 1px solid #B0B0B0;
        color: #444;
        font-size: 16px;
        font-weight: bold;
        padding: 3px 10px;
        text-align:center;
    }
    
    /*------------------------------------------------------------------------------------------------------------------------*/
    div.popup-position {
                position: fixed;
                top: 0;
                left: 0;
                background: rgba(0,0,0,0.7);
                width: 100%;
                height: 100%;
                display: none;
            }

            div#popup-wrapper {
                width: auto;
                height: auto;
                margin: 70px 70px;
                text-align: center;
            }

            button {
                border-radius: 5px;
                font-variant-caps: all-petite-caps;
            }

                button:hover {
                    border-radius: 5px;
                    transition: all 0.9s ease-in-out;
                }

            table {
                border-collapse: collapse;
                /*width: 100%;*/
                width: 900px;
                position: center;
                box-shadow: 5px 8px 15px 6px rgba(0,0,0,0.2);
                div #grad1;

            {
                border-radius: 10px;
                height: 200px;
                /*background: white;*/ /* For browsers that do not support gradients */
                background: linear-gradient(white, lightgray); /* Standard syntax (must be last) */
                width: 900px;
                height: auto;
                margin: 10px auto;
            }

            div#background {
                border-radius: 20px;
                margin-top: 10px;
                display: inline-block;
                background: #DCDCDC;
                flood-opacity: initial;
                width: 930px;
                height: auto;
                position: center;
            }

            label {
                display: block;
                border: 1px solid lightgray;
                background: lightgray;
                width: 100px;
                height: 30px;
                color: black;
                margin-bottom: 30px;
                margin-right: 30px;
                border-radius: 8px;
                float: right;
                text-decoration-style: none;
                text-align: center;
                padding: 3px 3px;
            }

                label:hover {
                    background: white;
                    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                }


            a {
                text-decoration: none;
                color: black;
                font-family: inherit;
                font-size: 13px;
            }

                a:hover {
                    text-decoration: none;
                    box-decoration-break: slice;
                    color: black;
                }

            form {
                float: right;
                /*margin-left: -10px;*/
                font-weight: bolder;
                font-size: 50px;
                color: white;
                margin: 0;
            }

                form a {
                    color: white;
                }
</style>
<script type="text/javascript">
    function toggle_visibility(id) {
        var e = document.getElementById(id);
        if (e.style.display == 'block')
            e.style.display = 'none';
        else
            e.style.display = 'block';
    }
   
</script>
</style>
<h1>Issuance</h1>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Customer Name")
        </th>
        <th>
            @Html.DisplayName("Item Name")
        </th>
        <th>
            @Html.DisplayName("Control#")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
           @Html.DisplayFor(modelItem => item.Customer_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Item_Name)
        </td>
        <td>
                        @using (Html.BeginForm("Create", "issuances",FormMethod.Post, new { id = item.Picking_Ordering_PutAway_Receiving_Control_}))
            {
                using (Html.BeginForm("table", "issuances", FormMethod.Post, new { id = item.Picking_Ordering_PutAway_Receiving_Control_ }))
                {}
            using (Html.BeginForm("Details", "issuances", FormMethod.Post, new { id = item.Customer_ID}))
            {
                <button onclick="toggle_visibility('popup-box1')"><a href="@Url.Action("Create", "issuances", new {id=item.Picking_Ordering_PutAway_Receiving_Control_})">@Html.DisplayFor(modelItem => item.Picking_Ordering_PutAway_Receiving_Control_)</a></button>
            }
            }
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Picking_Ordering_PutAway_Receiving_Control_ }) |
            @Html.ActionLink("Details", "Details", new { id=item.Picking_Ordering_PutAway_Receiving_Control_ }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Picking_Ordering_PutAway_Receiving_Control_ })
        </td>*@
    </tr>
}
</table>

wms(mysql)/Views/issuances/table.cshtml
@model IEnumerable<wms_mysql_.Models.issuance>
<style type="text/css">
    tr, table, th, td {
        border: 10px thick;
        border-collapse: collapse;
        padding: 7px;
        border-spacing: 5px;
    }

    td {
        padding: 15px;
    }

        tr:hover, td:hover {
            background-color: #6e7f9d;
        }

    th {
        background: -moz-linear-gradient(top, #F0F0F0 0, #DBDBDB 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #F0F0F0), color-stop(100%, #DBDBDB));
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#F0F0F0', endColorstr='#DBDBDB', GradientType=0);
        border: 1px solid #B0B0B0;
        color: #444;
        font-size: 16px;
        font-weight: bold;
        padding: 3px 10px;
        margin-right:20px;
    }
</style>
<script type="text/javascript">
    $(function () {

        $('#action-save').bind('click', function (event) {
            $('#myform').submit();
            return false;
        });

    });
</script>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Item_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number_of_Items)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Item_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number_of_Items)
        </td>
        <td>
            @using (Html.BeginForm("Confirm", "issuances", FormMethod.Post, new { id=item.Picking_Ordering_PutAway_Receiving_Control_, columnid = item.column_ID, columnname = item.column_name }))
            {
                <input type="submit" value="Close Transaction" onclick="@Url.Action("Confirm", "issuances", new { id = item.Picking_Ordering_PutAway_Receiving_Control_, columnid = item.column_ID, columnname = item.column_name })" />
            }
            
             @*@Html.ActionLink("Confirm", "Confirm", new { id = item.Picking_Ordering_PutAway_Receiving_Control_ }, new { @class = "btn btn-primary", @style = "color:white" })*@
        </td>
    </tr>
}

</table>